id: ID1641BA1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T22:00:41+00:00'
last_modified: '2022-06-08T02:01:58.919968+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22120
  title: ཆོས་སྐྱབས་དཔལ་བཟང་གི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4D15:
      image_group_id: I3540
      title: ''
      total_pages: 344
      order: 1
      base_file: 4D15.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
