id: P004573
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:42:20.996995
source_metadata:
  id: bdr:W22120
  title: ཆོས་སྐྱབས་དཔལ་བཟང་གི་རྣམ་ཐར
  author: ''
  volumes:
    ac5e39a3517e4fe1832a79cd9c137dc9:
      image_group_id: I3540
      title: ''
      volume_number: 1
      total_pages: 344
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
